language: php

git:
  depth: 1

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

env:
  global:
    - COMPOSER_ALLOW_XDEBUG=0

matrix:
  include:
    - php: 7.1
    - php: 7.2
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - composer update $COMPOSER_FLAGS --no-interaction

script:
  - php vendor/bin/phpunit
